apiVersion: v1
kind: Service
metadata:
  name: mysimple-service
spec:
  type: NodePort
  selector:
    app: mysimple-app
  ports:
  - protocol: TCP
    port: 3000
    targetPort: 3000
    nodePort: 30081
